#!/bin/sh

# Author: Foundation for Learning Equality
#
# /etc/init.d/ka-lite

### BEGIN INIT INFO
# Provides:          kalite
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ka-lite daemon, a local Khan Academy content server
### END INIT INFO

set -e

if !(whoami | grep "root" -q)
then
	echo "You need to be root"
	exit 1
fi

PATH=/bin:/usr/bin:/sbin:/usr/sbin

# Commented out because it causes "no such file or directory" error on Raspbian default install
# ...not that the file is missing, some other component fails
# . /lib/lsb/init-functions

. /etc/default/ka-lite

case "$1" in
  start)
    # run ka-lite as another user, the one who generated this file
    su $KALITE_USER -s /bin/sh -c "$KALITE_COMMAND start $KALITE_OPTS"
    ;;
  stop)
    su $KALITE_USER -s /bin/sh -c "$KALITE_COMMAND stop $KALITE_OPTS"
    ;;
  restart)
    su $KALITE_USER -s /bin/sh -c "$KALITE_COMMAND stop $KALITE_OPTS"
    su $KALITE_USER -s /bin/sh -c "$KALITE_COMMAND start $KALITE_OPTS"
    ;;
  status)
    su $KALITE_USER -s /bin/sh -c "$KALITE_COMMAND status $KALILTE_OPTS"
    ;;
  *)
    echo "Usage: /etc/init.d/kalite {start|stop|restart|status}" >&2
    exit 1
esac

