#!/usr/bin/dh-exec
debian/kalite.conf => /etc/nginx/sites-available/kalite.conf
debian/init-service => /usr/share/kalite/init-service
debian/etc-default => /etc/default/ka-lite
debian/ka-lite-raspberry-pi.server_options => /etc/ka-lite/server_options

# Removed because the nginx postinst script tries to start nginx before
# we have diverted its configuration. So we place the file in preinst !
# debian/nginx.conf => /etc/nginx/nginx.conf
